<?php
session_start();
include("config.php");
$tid=$_POST["tid"];
$name=$_POST["name"];
$num=$_POST["num"];
$day=$_POST["day"];
$month=$_POST["month"];
$year=$_POST["year"];
$sql="select * from tours";
$result=mysqli_query($conn,$sql);
while($row=mysqli_fetch_array($result))
{
	if("$row[name]"==$name)
		$price="$row[price]";
}
$total=$num*$price;
$_SESSION["tid"]=$tid;
$_SESSION["name"]=$name;
$_SESSION["num"]=$num;
$_SESSION["day"]=$day;
$_SESSION["month"]=$month;
$_SESSION["year"]=$year;
$_SESSION["price"]=$year;
$_SESSION["total"]=$total;
if($total==0)
	header("location:../invalid.html");
else
	header("location:../bill.php");
?>